# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attention_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Attention_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 200)
        MainWindow.setMaximumSize(QtCore.QSize(400, 200))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 30, 301, 61))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_yes = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_yes.setGeometry(QtCore.QRect(40, 110, 71, 21))
        self.pushButton_yes.setObjectName("pushButton_yes")
        self.pushButton_no = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_no.setGeometry(QtCore.QRect(270, 110, 71, 21))
        self.pushButton_no.setObjectName("pushButton_no")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "关注窗体"))
        self.pushButton_yes.setText(_translate("MainWindow", "确认"))
        self.pushButton_no.setText(_translate("MainWindow", "取消"))
