# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(320, 50, 381, 321))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 379, 319))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 381, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 50, 261, 321))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 190, 261, 31))
        self.label.setObjectName("label")
        self.listView = QtWidgets.QListView(self.frame)
        self.listView.setGeometry(QtCore.QRect(0, 230, 261, 91))
        self.listView.setObjectName("listView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 261, 181))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 18))
        self.menubar.setProperty("menu", False)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_sys = QtWidgets.QMenu(self.menubar)
        self.menu_sys.setObjectName("menu_sys")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_heat_2 = QtWidgets.QAction(MainWindow)
        self.action_heat_2.setObjectName("action_heat_2")
        self.action_evaluate = QtWidgets.QAction(MainWindow)
        self.action_evaluate.setObjectName("action_evaluate")
        self.action_price = QtWidgets.QAction(MainWindow)
        self.action_price.setObjectName("action_price")
        self.action_up = QtWidgets.QAction(MainWindow)
        self.action_up.setObjectName("action_up")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_out_2 = QtWidgets.QAction(MainWindow)
        self.action_out_2.setObjectName("action_out_2")
        self.menu.addAction(self.action_heat_2)
        self.menu.addAction(self.action_evaluate)
        self.menu.addAction(self.action_price)
        self.menu.addAction(self.action_up)
        self.menu_sys.addAction(self.action_about)
        self.menu_sys.addAction(self.action_out_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_sys.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "              关注商品列表"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.menu_sys.setTitle(_translate("MainWindow", "系统"))
        self.action_heat_2.setText(_translate("MainWindow", "外设产品热卖榜"))
        self.action_evaluate.setText(_translate("MainWindow", "关注商品--中差评预警"))
        self.action_price.setText(_translate("MainWindow", "关注商品--价格变化预警"))
        self.action_up.setText(_translate("MainWindow", "更新关注商品信息"))
        self.action_about.setText(_translate("MainWindow", "关于"))
        self.action_out_2.setText(_translate("MainWindow", "退出"))
